version: '3.9'

services:
  env_gradle_kotlin:
    container_name: env_gradle_kotlin
    build: .
    image: env_gradle_kotlin
    hostname: env_gradle_kotlin
    volumes:
      - ./workspace:/workspace
